# Generated by Django 4.1 on 2023-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assesments_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assid', models.CharField(max_length=250)),
                ('ass_name', models.CharField(max_length=20)),
                ('ass_point', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AssMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markS_id', models.CharField(max_length=250)),
                ('markClassId', models.CharField(max_length=20)),
                ('markAssName', models.CharField(max_length=20)),
                ('MarkAss', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greadS_id', models.CharField(max_length=250)),
                ('greadClassId', models.CharField(max_length=200)),
                ('greadtotalmark', models.CharField(max_length=20)),
                ('greadLetter', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lms_wieght',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=250)),
                ('asses_name', models.CharField(max_length=20)),
                ('co_name', models.CharField(default='null', max_length=20)),
                ('asses_point', models.FloatField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='usersemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('semestername', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='weight_ass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieghtClassid', models.CharField(max_length=250)),
                ('totalweight', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='wieght_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(default='null', max_length=250)),
                ('Exam_name', models.CharField(default='null', max_length=20)),
                ('wieght', models.FloatField(default='null', max_length=20)),
                ('taken', models.FloatField(default='null', max_length=3)),
                ('ratio', models.FloatField(default='null', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='wieght_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalClassid', models.CharField(max_length=250)),
                ('totalAsses_name', models.CharField(max_length=20)),
                ('totalCo_name', models.CharField(default='null', max_length=20)),
                ('totalpoint', models.FloatField(default='0', max_length=3)),
            ],
        ),
    ]
