# Generated by Django 4.1 on 2023-03-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roulesname', models.CharField(max_length=250)),
                ('roulesPoint', models.CharField(max_length=50)),
            ],
        ),
    ]
