# Generated by Django 4.1 on 2023-03-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_roule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roule',
            new_name='rouleW',
        ),
    ]
