# Generated by Django 4.1 on 2023-03-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_roule_roulew'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoMarkClassId', models.CharField(max_length=20)),
                ('CoMarkconame', models.CharField(max_length=20)),
                ('CoMarks', models.CharField(max_length=20)),
            ],
        ),
    ]
