# Generated by Django 4.1 on 2022-10-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminemail', models.CharField(max_length=40)),
                ('adminpass', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('problem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=40)),
                ('userpass', models.CharField(max_length=40)),
            ],
        ),
    ]
