# Generated by Django 4.1 on 2022-10-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachemail', models.CharField(max_length=40)),
                ('teachpass', models.CharField(max_length=40)),
            ],
        ),
    ]
