# Generated by Django 4.1 on 2023-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lms_wieght',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=20)),
                ('asses_name', models.CharField(max_length=20)),
                ('co_name', models.CharField(default='null', max_length=20)),
                ('asses_point', models.FloatField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='wieght_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(default='null', max_length=20)),
                ('Exam_name', models.CharField(default='null', max_length=20)),
                ('wieght', models.CharField(default='null', max_length=20)),
                ('taken', models.CharField(default='null', max_length=3)),
                ('ratio', models.CharField(default='null', max_length=3)),
            ],
        ),
    ]
