# Generated by Django 4.1 on 2023-01-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_lms_wieght_wieght_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wieght_number',
            name='ratio',
            field=models.FloatField(default='null', max_length=3),
        ),
        migrations.AlterField(
            model_name='wieght_number',
            name='taken',
            field=models.FloatField(default='null', max_length=3),
        ),
        migrations.AlterField(
            model_name='wieght_number',
            name='wieght',
            field=models.FloatField(default='null', max_length=20),
        ),
    ]
