# Generated by Django 4.1 on 2023-02-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_wieght_number_ratio_alter_wieght_number_taken_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assesments',
            new_name='assesments_mark',
        ),
    ]
