# Generated by Django 4.1 on 2023-02-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_wieght_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieghtClassid', models.CharField(max_length=20)),
                ('totalweight', models.FloatField(max_length=20)),
            ],
        ),
    ]
