# Generated by Django 4.1 on 2023-02-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='weight',
            new_name='weight_ass',
        ),
    ]
