# Generated by Django 4.1 on 2023-02-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_rename_weight_weight_ass'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markS_id', models.CharField(max_length=20)),
                ('markClassId', models.CharField(max_length=20)),
                ('markAssName', models.CharField(max_length=20)),
                ('MarkAss', models.CharField(max_length=20)),
            ],
        ),
    ]
