# Generated by Django 4.1 on 2023-02-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mark',
            new_name='AssMark',
        ),
    ]
