# Generated by Django 4.1 on 2023-02-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_rename_mark_assmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='gread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greadS_id', models.CharField(max_length=20)),
                ('greadClassId', models.CharField(max_length=20)),
                ('greadtotalmark', models.CharField(max_length=20)),
                ('greadLetter', models.CharField(max_length=20)),
            ],
        ),
    ]
