# Generated by Django 4.1 on 2023-03-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_assmark_marks_id_alter_gread_greads_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesments_mark',
            name='assid',
            field=models.CharField(max_length=250),
        ),
    ]
