# Generated by Django 4.1 on 2023-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_assesments_mark_assid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gread',
            name='greadClassId',
            field=models.CharField(max_length=250),
        ),
    ]
