# Generated by Django 4.1 on 2023-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_gread_greadclassid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gread',
            name='greadClassId',
            field=models.CharField(max_length=350),
        ),
    ]
