# Generated by Django 4.1 on 2023-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_alter_gread_greadclassid'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('semester', models.CharField(max_length=250)),
            ],
        ),
    ]
