# Generated by Django 4.1 on 2023-03-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_usersemester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersemester',
            old_name='semester',
            new_name='semestername',
        ),
    ]
